package com.oasys.digihealth.doctor.ui.quickregistration.model


data class RegistrationUatSaveRequest(
    var address_line1: String? = "",
    var address_line2: String? = "",
    var age: Int? = 0,
    var block_uuid: Int? = 0,
    var country_uuid: Int? = 0,
    var department_uuid: String? = "",
    var speciality_department_uuid: String? = "",
    var district_uuid: Int? = 0,
    var dob: String? = "",
    var first_name: String? = "",
    var middle_name: String? = "",
    var last_name: String? = "",
    var gender_uuid: Int? = 0,
    var ili: Boolean? = false,
    var is_adult: Int? = 0,
    var patient_scheme_uuid: Int? = null,
    var is_dob_auto_calculate: Int? = 0,
    var isDrMobileApi: Int? = 0,
    var is_rapid_test: Boolean? = false,
    var is_maternity: Boolean? = false,
    var mobile: String? = "",
    var no_symptom: Boolean? = false,
    var period_uuid: Int? = 0,
    var pincode: String? = "",
    var registred_facility_uuid: String? = "",
    var sample_type_uuid: Int? = 0,
    var sari: Boolean? = false,
    var saveExists: Boolean? = false,
    var session_uuid: Int? = 0,
    var state_uuid: Int? = 0,
    var unit_uuid: Int? = 0,
    var title_uuid: Int? = 0,
    var suffix_uuid: Int? = 0,
    var community_uuid: Int? = 0,
    var taluk_uuid: String? = "",
    var village_uuid: String? = "",
    var father_name: String? = null,
    var aadhaar_number: String? = "",
    var remarks: String? = "",
    var email: String? = "",
    var fingerPrintData: Any = Any(),
    var professional_title_uuid: Int? = 0,
    var lab_to_facility_uuid: Int = 0,
    var tat_start_time: String = "",
    var tat_end_time: String = ""
)