package com.oasys.digihealth.doctor.ui.quickregistration.model

data class SchemaName(
    var address_1: String? = null,
    var address_2: String? = null,
    var address_3: String? = null,
    var business_reg_no: String? = null,
    var code: String? = null,
    var contact_number: String? = null,
    var country_uuid: Int? = null,
    var created: Created? = null,
    var created_by: Int? = null,
    var created_date: String? = null,
    var credit_limit: String? = null,
    var district_uuid: Int? = null,
    var email_id: String? = null,
    var end_date: String? = null,
    var gst_number: String? = null,
    var is_active: Boolean? = null,
    var is_gst_registered: Boolean? = null,
    var modified: Modified? = null,
    var modified_by: Int? = null,
    var modified_date: String? = null,
    var name: String? = null,
    var pincode: String? = null,
    var revision: Int? = null,
    var scheme_type: SchemeType? = null,
    var scheme_type_uuid: Int? = null,
    var start_date: String? = null,
    var state_uuid: Int? = null,
    var status: Boolean? = null,
    var uuid: Int? = null,
    var vw_country_info: VwCountryInfo? = null,
    var vw_district_info: VwDistrictInfo? = null,
    var vw_state_info: VwStateInfo? = null
)