package com.oasys.digihealth.doctor.ui.helpdesk.model

data class AddTicketRequestModel(
    var assest_uuid: Int? = 0,
    var application_user_uuid: Int? = 0,
    var created_by: Int? = 0,
    var ticketstatus_uuid: Int? = 0,
    var user_type_uuid: Int? = 0,
    var department_uuid: Int? = 0,
    var facility_uuid: Int? = 0,
    var asset_description: Int? = 0,
    var priority_uuid: Int? = 0,
    var asset_code: String? = "",
    var vendorMail: String? = "",
    var assignto: Int? = 0,
    var problem_description: String? = "",
    var subject: String? = "",
    var make: String? = "",
    var model: String? = "",
    var serial: String? = "",
    var mobile: String? = "",
    var pin: String? = "",
    var ticket_details_priority_uuid: Int? = 0,
    var ticket_details_priority_code: String? = "",
    var ticket_details_priority_name: String? = "",
    var help_desk_category_uuid: Int? = 0,
    var category_uuid: Int? = 0,
    var subcategory_uuid: Int? = 0,
    var ticketmanagment_uuid: Int? = 0,
    var priority: Int? = 0,
    var vendor_uuid: Int? = 0,
    var help_desk_category_name: String? = "",
    var grofficer_name: String? = "",
    var grofficer_no: String? = "",
    var grofficer_mail: String? = ""
)