package com.oasys.digihealth.doctor.ui.helpdesk.model

import com.oasys.digihealth.doctor.ui.helpdesk.model.ActivityModel.TicketDetail


data class TicketListResponseContent(
    val uuid: Int? = 0,
    val help_desk_management_uuid: Int? = 0,
    val application_user_uuid: Int? = 0,
    val vendor_uuid: Int? = 0,
    val public_user_uuid: Int? = 0,
    val user_type_uuid: Int? = 0,
    val subject: String? = "",
    val problem_description: String? = "",
    val category_uuid: Int? = 0,
    val subcategory_uuid: Int? = 0,
    val facility_uuid: Int? = 0,
    val department_uuid: Int? = 0,
    val assest_uuid: Int? = 0,
    val ticket_id: String? = "",
    val asset_code: String? = "",
    val make: String? = "",
    var ticket_details: List<TicketDetail>? = null,
    val model: String? = "",
    val serial: String? = "",
    val rating_uuid: Int? = 0,
    val status: Boolean? = false,
    val revision: String? = "",
    val created_by: String? = "",
    val created_date: String? = "",
    val modified_by: Int? = 0,
    val modified_date: String? = "",
    val help_desk_category_uuid: Int? = 0,
    val help_desk_category_name: String? = "",
    val sub_category_uuid: Int? = 0,
    val sub_category_name: String? = "",
    val ticket_details_uuid: Int? = 0,
    val ticket_details_ticketmanagment_uuid: Int? = 0,
    val ticket_detail_priority_uuid: Int? = 0,
    val priority_uuid: Int? = 0,
    val ticket_details_assignto: String? = "",
    val ticket_details_attachment: String? = "",
    val ticket_details_ticketstatus_uuid: Int? = 0,
    val ticket_details_comments: String? = "",
    val ticket_details_rating_uuid: Int? = 0,
    val ticket_details_close_comments: String? = "",
    val ticket_details_is_open: Boolean? = false,
    val ticket_details_revision: String? = "",
    val ticket_details_status: Boolean? = false,
    val ticket_details_created_by: String? = "",
    val ticket_details_modified_by: String? = "",
    val ticket_details_created_date: String? = "",
    val ticket_details_modified_date: String? = "",
    val ticket_details_priority_uuid: Int? = 0,
    val ticket_details_priority_code: String? = "",
    val ticket_details_priority_name: String? = "",
    val ticket_details_priority_status: Boolean? = false,
    val ticket_details_priority_is_active: Boolean? = false,
    val ticket_details_priority_rev: Boolean? = false,
    val ticket_details_priority_created_by: String? = "",
    val ticket_details_priority_modified_by: String? = "",
    val ticket_details_priority_created_date: String? = "",
    val ticket_details_priority_modified_date: String? = "",
    val institution_uuid: String? = "",
    val institution_code: String? = "",
    val institution_name: String? = "",
    val users_uuid: Int? = 0,
    val users_first_name: String? = "",
    val users_middle_name: String? = "",
    val users_last_name: String? = "",
    val ticket_created_by: String? = "",
    val ticket_details_ticket_status_uuid: Int? = 0,
    val ticket_details_ticket_status_code: String? = "",
    val ticket_details_ticket_status_name: String? = "",
    val facility_name: String? = "",
    val department_name: String? = "",
    val createdby_detail: CreatedDetails? = null

) {
    data class CreatedDetails(
        val first_name: String? = "",
        val user_name: String? = ""
    )
}