package com.oasys.digihealth.doctor.ui.out_patient.model.responseaddpatient

data class Patients(
    var age: Int? = 0,
    var applicationType: String? = "",
    var application_type_uuid: Int? = 0,
    var blood_group_uuid: Int? = 0,
    var created_by: String? = "",
    var created_date: String? = "",
    var department_uuid: String? = "",
    var dob: String? = "",
    var first_name: String? = "",
    var gender_uuid: Int? = 0,
    var is_active: Int? = 0,
    var is_adult: Boolean? = false,
    var is_dob_auto_calculate: Int? = 0,
    var is_mlc: Int? = 0,
    var last_name: String? = "",
    var middle_name: String? = "",
    var modified_by: String? = "",
    var modified_date: String? = "",
    var old_pin: Long? = 0,
    var package_uuid: Int? = 0,
    var patientType: String? = "",
    var patient_type_uuid: Int? = 0,
    var period_uuid: Int? = 0,
    var professional_title_uuid: Int? = 0,
    var registered_date: String? = "",
    var registred_facility_uuid: String? = "",
    var revision: Int? = 0,
    var session_uuid: Int? = 0,
    var suffix_uuid: Int? = 0,
    var tat_end_time: String? = "",
    var tat_start_time: String? = "",
    var title_uuid: Int? = 0,
    var uhid: String? = ""
)