package com.oasys.digihealth.doctor.ui.out_patient.model.responseaddpatient

data class PatientDetails(
    var aadhaar_number: String? = "",
    var address_line1: String? = "",
    var address_line2: String? = "",
    var address_line3: String? = "",
    var address_line4: String? = "",
    var address_line5: String? = "",
    var alternate_number: String? = "",
    var block_uuid: Int? = 0,
    var community_uuid: Int? = 0,
    var country_uuid: Int? = 0,
    var created_by: String? = "",
    var created_date: String? = "",
    var district_uuid: Int? = 0,
    var email: String? = "",
    var height: String? = "",
    var ili: Int? = 0,
    var is_rapid_test: Int? = 0,
    var lab_to_facility_uuid: Int? = 0,
    var mobile: String? = "",
    var modified_by: String? = "",
    var modified_date: String? = "",
    var no_symptom: Int? = 0,
    var photo_path: String? = "",
    var pincode: String? = "",
    var revision: Int? = 0,
    var sample_type_uuid: Int? = 0,
    var sari: Int? = 0,
    var smart_ration_number: String? = "",
    var state_uuid: Int? = 0,
    var taluk_uuid: Int? = 0,
    var village_uuid: Int? = 0,
    var weight: String? = ""
)