package com.hmis_tn.doctor.ui.emr_workflow.treatment_kit.model.drug_info

data class ResponseContent(
    var bar_code_id: Any? = Any(),
    var base_uom_uuid: Int? = 0,
    var batch_id: String? = "",
    var cgst_uuid: Int? = 0,
    var cost_price: String? = "",
    var created_by: Int? = 0,
    var created_date: String? = "",
    var discount: String? = "",
    var discount_mode_uuid: Int? = 0,
    var expiry_date: String? = "",
    var expiry_updated_by: Int? = 0,
    var expiry_updated_date: Any? = Any(),
    var facility_uuid: Int? = 0,
    var grn_detail_uuid: Int? = 0,
    var grn_uuid: Int? = 0,
    var gst_uuid: Int? = 0,
    var is_active: Boolean? = false,
    var is_expiry_updated: Boolean? = false,
    var is_suspended: Boolean? = false,
    var item_master_uuid: Int? = 0,
    var modified_by: Int? = 0,
    var modified_date: String? = "",
    var purchase_uom_uuid: Int? = 0,
    var quantity: Int? = 0,
    var revision: Int? = 0,
    var sale_price: String? = "",
    var sale_uom_uuid: Int? = 0,
    var sgst_uuid: Int? = 0,
    var status: Boolean? = false,
    var stock_entry_detail_uuid: Int? = 0,
    var stock_entry_uuid: Int? = 0,
    var stock_item_uuid: Int? = 0,
    var store_master: StoreMaster? = StoreMaster(),
    var store_master_uuid: Int? = 0,
    var unit_price: String? = "",
    var uom_price: String? = "",
    var uuid: Int? = 0
)