package com.oasys.digihealth.doctor.ui.helpdesk.model.ActivityModel

data class TicketActivityList(
    var application_user_uuid: Int? = null,
    var assest_uuid: Int? = null,
    var asset_code: String? = null,
    var category_uuid: Int? = null,
    var created_by: Int? = null,
    var created_date: String? = null,
    var createdby_detail: CreatedbyDetail? = null,
    var department_name: String? = null,
    var department_uuid: Int? = null,
    var facility_name: String? = null,
    var facility_uuid: Int? = null,
    var help_desk_category: HelpDeskCategory? = null,
    var help_desk_management_uuid: Int? = null,
    var make: String? = null,
    var model: String? = null,
    var modified_by: Int? = null,
    var modified_date: String? = null,
    var problem_description: String? = null,
    var public_user_uuid: Int? = null,
    var rating_uuid: Int? = null,
    var revision: Any? = null,
    var serial: String? = null,
    var status: Boolean? = null,
    var sub_category: SubCategory? = null,
    var subcategory_uuid: Int? = null,
    var subject: String? = null,
    var ticket_details: List<TicketDetail>? = null,
    var ticket_id: String? = null,
    var ticket_management_complaint_documents: List<TicketManagementComplaintDocument>? = null,
    var ticket_management_solution_documents: List<Any>? = null,
    var user_type_uuid: Int? = null,
    var uuid: Int? = null,
    var vendor_uuid: Int? = null
)