package com.hmis_tn.doctor.ui.emr_workflow.treatment_kit.model

data class LabCreated(
    val auth_status_uuid: Any? = Any(),
    val cancel_reason_comment: Any? = Any(),
    val cancel_reason_uuid: Any? = Any(),
    val cancelled_by: Any? = Any(),
    val cancelled_date_time: Any? = Any(),
    val consultation_uuid: Int? = 0,
    val created_by: Int? = 0,
    val created_date: String? = "",
    val department_uuid: Int? = 0,
    val doctor_uuid: Int? = 0,
    val encounter_doctor_uuid: Any? = Any(),
    val encounter_type_uuid: Int? = 0,
    val encounter_uuid: Int? = 0,
    val facility_uuid: Int? = 0,
    val from_facility_name: Any? = Any(),
    val is_active: Boolean? = false,
    val is_direct_bill: Any? = Any(),
    val is_visible_from_facility: Boolean? = false,
    val is_visible_to_facility: Boolean? = false,
    val lab_master_type_uuid: Int? = 0,
    val modified_by: Int? = 0,
    val modified_date: String? = "",
    val order_completed_date: Any? = Any(),
    val order_number: Int? = 0,
    val order_request_date: String? = "",
    val order_schedule_date: Any? = Any(),
    val order_status_uuid: Int? = 0,
    val order_to_location_uuid: Int? = 0,
    val package_uuid: Any? = Any(),
    val patient_treatment_uuid: Int? = 0,
    val patient_uuid: Int? = 0,
    val revision: Int? = 0,
    val status: Boolean? = false,
    val sub_department_uuid: Int? = 0,
    val tat_session_end: Any? = Any(),
    val tat_session_start: Any? = Any(),
    val uuid: Int? = 0,
    val ward_uuid: Any? = Any()
)