package com.hmis_tn.doctor.ui.out_patient.search_response_model

data class InPatientResponseModel(
    val msg: String? = null,
    val req: Req? = null,
    val responseContents: List<InPatientResponseData?>? = null,
    val status: String? = null,
    val statusCode: Int? = null,
    val totalRecords: Int? = null
)

data class Req(
    val department_name: String? = null,
    val facility_uuid: String? = null,
    val itemsPerPage: Int? = null,
    val offset: Int? = null,
    val orderColumn: String? = null,
    val pageNo: Int? = null,
    val paginationSize: Int? = null,
    val search: String? = null,
    val sortField: String? = null,
    val sortOrder: String? = null,
    val ward_name: String? = null
)


data class InPatientResponseData(
    val admission_admission_request_uuid: Int? = null,
    val admission_admission_status_code: String? = null,
    val admission_admission_status_name: String? = null,
    val admission_bed_uuid: Int? = null,
    val admission_billing_required: AdmissionBillingRequired? = null,
    val admission_code: String? = null,
    val admission_community_uuid: Int? = null,
    val admission_created_by: Int? = null,
    val admission_created_date: String? = null,
    val admission_date: String? = null,
    val admission_death_type_uuid: Any? = null,
    val admission_department_uuid: Int? = null,
    val admission_diagnosis_uuid: Int? = null,
    val admission_diet_uuid: Int? = null,
    val admission_discharge_date: Any? = null,
    val admission_doctor_first_name: String? = null,
    val admission_doctor_last_name: Any? = null,
    val admission_doctor_middle_name: Any? = null,
    val admission_doctor_username: String? = null,
    val admission_doctor_uuid: Int? = null,
    val admission_encounter_type_uuid: Int? = null,
    val admission_encounter_uuid: Int? = null,
    val admission_facility_location_uuid: Any? = null,
    val admission_insurance_number: String? = null,
    val admission_insurance_type_uuid: Int? = null,
    val admission_insurance_uuid: Int? = null,
    val admission_is_active: AdmissionIsActive? = null,
    val admission_is_cancelled_admission: AdmissionIsCancelledAdmission? = null,
    val admission_is_casualty: AdmissionIsCasualty? = null,
    val admission_modified_by: Int? = null,
    val admission_patient_category_uuid: Int? = null,
    val admission_patient_uuid: Int? = null,
    val admission_priority_uuid: Any? = null,
    val admission_reason: String? = null,
    val admission_refer_type_uuid: Any? = null,
    val admission_referrer_uuid: Any? = null,
    val admission_religion_uuid: Int? = null,
    val admission_request_admission_facility_uuid: Any? = null,
    val admission_request_admission_status_code: Any? = null,
    val admission_request_admission_status_name: Any? = null,
    val admission_request_admission_status_uuid: Any? = null,
    val admission_request_admitting_reason_uuid: Any? = null,
    val admission_request_created_by: Any? = null,
    val admission_request_created_date: Any? = null,
    val admission_request_department_uuid: Any? = null,
    val admission_request_doctor_first_name: Any? = null,
    val admission_request_doctor_last_name: Any? = null,
    val admission_request_doctor_middle_name: Any? = null,
    val admission_request_doctor_username: Any? = null,
    val admission_request_doctor_uuid: Any? = null,
    val admission_request_encounter_uuid: Any? = null,
    val admission_request_from_facility: Any? = null,
    val admission_request_is_active: Any? = null,
    val admission_request_modified_by: Any? = null,
    val admission_request_modified_date: Any? = null,
    val admission_request_patient_uuid: Any? = null,
    val admission_request_remarks: Any? = null,
    val admission_request_requested_date: Any? = null,
    val admission_request_status: Any? = null,
    val admission_request_uuid: Any? = null,
    val admission_request_ward_uuid: Any? = null,
    val admission_room_uuid: Int? = null,
    val admission_status: AdmissionStatus? = null,
    val admission_status_uuid: Int? = null,
    val admission_unit_code: String? = null,
    val admission_unit_name: String? = null,
    val admission_unit_uuid: Int? = null,
    val admission_uuid: Int? = null,
    val admission_ward_uuid: Int? = null,
    val alleged_history_code: Any? = null,
    val alleged_history_name: Any? = null,
    val alleged_history_uuid: Any? = null,
    val animal_attack_code: Any? = null,
    val animal_attack_name: Any? = null,
    val animal_attack_uuid: Any? = null,
    val ar_department_code: Any? = null,
    val ar_department_name: Any? = null,
    val ar_department_short_code: Any? = null,
    val ar_gender_uuid: Any? = null,
    val ar_patient_age: Any? = null,
    val ar_patient_auto_dob: Any? = null,
    val ar_patient_dob: Any? = null,
    val ar_patient_first_name: Any? = null,
    val ar_patient_gender_code: Any? = null,
    val ar_patient_gender_name: Any? = null,
    val ar_patient_last_name: Any? = null,
    val ar_patient_middle_name: Any? = null,
    val ar_patient_mobile: Any? = null,
    val ar_patient_registered_date: Any? = null,
    val ar_patient_registred_facility_uuid: Any? = null,
    val ar_patient_title_code: Any? = null,
    val ar_patient_title_name: Any? = null,
    val ar_patient_uhid: Any? = null,
    val ar_patients_uuid: Any? = null,
    val ar_ward_master_code: Any? = null,
    val ar_ward_master_name: Any? = null,
    val arrival_mode_code: Any? = null,
    val arrival_mode_name: Any? = null,
    val arrival_mode_uuid: Any? = null,
    val attender_relation_code: String? = null,
    val attender_relation_name: String? = null,
    val case_type_code: Any? = null,
    val case_type_name: Any? = null,
    val casetype_uuid: Any? = null,
    val community_code: Any? = null,
    val community_name: Any? = null,
    val contact_number: Any? = null,
    val contact_person: Any? = null,
    val created_by_first_name: String? = null,
    val created_by_last_name: Any? = null,
    val created_by_middle_name: Any? = null,
    val created_by_user_name: String? = null,
    val department_code: String? = null,
    val department_name: String? = null,
    val department_short_code: String? = null,
    val diagnosis_code: Any? = null,
    val diagnosis_name: Any? = null,
    val diet_code: Any? = null,
    val diet_name: Any? = null,
    val doctor_department_name: String? = null,
    val doctor_department_uuid: Int? = null,
    val doctor_unit_name: Any? = null,
    val doctor_unit_uuid: Any? = null,
    val employee_no: Any? = null,
    val escorted_by_code: Any? = null,
    val escorted_by_name: Any? = null,
    val escortedby_uuid: Any? = null,
    val examination: Any? = null,
    val facility_code: String? = null,
    val facility_location_address_line1: Any? = null,
    val facility_location_address_line2: Any? = null,
    val facility_location_block_master_code: Any? = null,
    val facility_location_block_master_name: Any? = null,
    val facility_location_block_master_short_code: Any? = null,
    val facility_location_corporation_master_code: Any? = null,
    val facility_location_corporation_master_name: Any? = null,
    val facility_location_corporation_master_short_code: Any? = null,
    val facility_location_country_master_code: String? = null,
    val facility_location_country_master_name: String? = null,
    val facility_location_country_master_short_code: String? = null,
    val facility_location_dm_code: String? = null,
    val facility_location_dm_name: String? = null,
    val facility_location_hud_master_code: Any? = null,
    val facility_location_hud_master_name: Any? = null,
    val facility_location_hud_master_short_code: Any? = null,
    val facility_location_landline: String? = null,
    val facility_location_municipality_master_code: Any? = null,
    val facility_location_municipality_master_name: Any? = null,
    val facility_location_municipality_master_short_code: Any? = null,
    val facility_location_pincode: Int? = null,
    val facility_location_state_master_code: String? = null,
    val facility_location_state_master_name: String? = null,
    val facility_location_state_master_short_code: Any? = null,
    val facility_location_taluk_master_code: Any? = null,
    val facility_location_taluk_master_name: Any? = null,
    val facility_location_village_master_code: Any? = null,
    val facility_location_village_master_name: Any? = null,
    val facility_name: String? = null,
    val facility_uuid: Int? = null,
    val gender_uuid: Int? = null,
    val iden_mark: Any? = null,
    val identifier_type_code: Any? = null,
    val identifier_type_name: Any? = null,
    val incident_datetime: Any? = null,
    val incident_details: Any? = null,
    val income_code: Any? = null,
    val income_name: Any? = null,
    val informed_datetime: Any? = null,
    val insurance_master_code: Any? = null,
    val insurance_master_name: Any? = null,
    val insurance_type_code: Any? = null,
    val insurance_type_name: Any? = null,
    val marital_status_code: Any? = null,
    val marital_status_name: Any? = null,
    val mlc_no: Any? = null,
    val modified_by_first_name: String? = null,
    val modified_by_last_name: Any? = null,
    val modified_by_middle_name: Any? = null,
    val modified_by_user_name: String? = null,
    val modified_date: String? = null,
    val occupation_code: Any? = null,
    val occupation_name: Any? = null,
    val occupation_uuid: Int? = null,
    val other_proof_number: String? = null,
    val other_proof_uuid: Int? = null,
    val patient_aadhaar_number: String? = null,
    val patient_address_line1: String? = null,
    val patient_address_line2: String? = null,
    val patient_address_line3: String? = null,
    val patient_address_line4: String? = null,
    val patient_address_line5: String? = null,
    val patient_age: Int? = null,
    val patient_attender_contact_number: String? = null,
    val patient_attender_name: String? = null,
    val patient_auto_dob: PatientAutoDob? = null,
    val patient_category_code: Any? = null,
    val patient_category_name: Any? = null,
    val patient_district_uuid: Int? = null,
    val patient_dm_master_code: String? = null,
    val patient_dm_master_name: String? = null,
    val patient_dob: String? = null,
    val patient_first_name: String? = null,
    val patient_gender_code: String? = null,
    val patient_gender_name: String? = null,
    val patient_income_uuid: Int? = null,
    val patient_last_name: String? = null,
    val patient_marital_uuid: Int? = null,
    val patient_middle_name: String? = null,
    val patient_mobile: String? = null,
    val patient_pincode: String? = null,
    val patient_registered_date: String? = null,
    val patient_registred_facility_uuid: Int? = null,
    val patient_status_code: Any? = null,
    val patient_status_name: Any? = null,
    val patient_status_uuid: Any? = null,
    val patient_taluk_uuid: Int? = null,
    val patient_title_code: String? = null,
    val patient_title_name: String? = null,
    val patient_tm_master_code: String? = null,
    val patient_tm_master_name: String? = null,
    val patient_uhid: String? = null,
    val patient_village_uuid: Int? = null,
    val patient_vm_master_code: String? = null,
    val patient_vm_master_name: String? = null,
    val patients_uuid: Int? = null,
    val police_station: Any? = null,
    val relation_type_uuid: Int? = null,
    val religion_code: Any? = null,
    val religion_name: Any? = null,
    val vehicle_number: Any? = null,
    val ward_master_code: String? = null,
    val ward_master_name: String? = null,
    val wbm_bed_number: Any? = null,
    val wrs_room_code: Any? = null,
    val wrs_room_name: Any? = null,
    val wrs_room_number: Any? = null,
    val patient_info: Any? = null
)


data class AdmissionBillingRequired(
    val `data`: List<Int?>? = null,
    val type: String? = null
)


data class AdmissionIsActive(
    val `data`: List<Int?>? = null,
    val type: String? = null
)

data class AdmissionIsCancelledAdmission(
    val `data`: List<Int?>? = null,
    val type: String? = null
)

data class AdmissionIsCasualty(
    val `data`: List<Int?>? = null,
    val type: String? = null
)

data class AdmissionStatus(
    val `data`: List<Int?>? = null,
    val type: String? = null
)

data class PatientAutoDob(
    val `data`: List<Int?>? = null,
    val type: String? = null
)
