package com.oasys.digihealth.doctor.ui.emr_workflow.op_notes.model.prev_records.observed_values

data class ResponseContent(
    var activity_uuid: Any?,
    var category_key: String?,
    var category_uuid: Int?,
    var comments: String?,
    var concept_key: String?,
    var concept_uuid: Int?,
    var consultation_uuid: Int?,
    var created_by: Int?,
    var created_date: String?,
    var encounter_doctor_uuid: Int?,
    var encounter_type_uuid: Any?,
    var encounter_uuid: Int?,
    var entry_date: String?,
    var is_active: Boolean?,
    var modified_by: Int?,
    var modified_date: String?,
    var patient_uuid: Int?,
    var profile_section_category_concept_uuid: Int?,
    var profile_section_category_concept_value_uuid: Int?,
    var profile_section_category_uuid: Int?,
    var profile_section_uuid: Int?,
    var profile_type_uuid: Int?,
    var profile_uuid: Int?,
    var result_binary: String?,
    var result_path: String?,
    var result_value: String?,
    var result_value_json: String?,
    var result_value_rich_text: String?,
    var revision: Int?,
    var section_key: String?,
    var section_uuid: Int?,
    var status: Boolean?,
    var term_key: String?,
    var uuid: Int?
)