package com.hmis_tn.doctor.ui.emr_workflow.certificate.model

data class TemplatesResponseContent(
    val d_is_active: Boolean = false,
    val d_name: String = "",
    val d_status: Boolean = false,
    val d_uuid: Int = 0,
    val f_is_active: Boolean = false,
    val f_name: String = "",
    val f_status: Boolean = false,
    val f_uuid: Int = 0,
    val modified_date: String = "",
    val nt_code: String = "",
    val nt_created_by: Int = 0,
    val nt_created_date: String = "",
    val nt_data_template: String = "",
    val nt_department_uuid: Int = 0,
    val nt_facility_uuid: Int = 0,
    val nt_is_active: Boolean = false,
    val nt_is_default: Boolean = false,
    val nt_modified_by: Int = 0,
    val nt_name: String = "",
    val nt_note_template_type_uuid: Int = 0,
    val nt_note_type_uuid: Int = 0,
    val nt_revision: Int = 0,
    val nt_status: Boolean = false,
    val nt_uuid: Int = 0,
    val ntt_is_active: Boolean = false,
    val ntt_name: String = "",
    val ntt_status: Boolean = false,
    val ntt_uuid: Int = 0,
    val nty_is_active: Boolean = false,
    val nty_name: String = "",
    val nty_status: Boolean = false,
    val nty_uuid: Int = 0
)