package com.hmis_tn.doctor.ui.emr_workflow.ot_schedule.model.responseaddsurgery

data class GetSurgeryPinresponseContent(
    val age: Int? = 0,
    val application_identifier: Any? = Any(),
    val application_type_uuid: Int? = 0,
    val application_uuid: Any? = Any(),
    val blood_group_uuid: Any? = Any(),
    val created_by: Int? = 0,
    val created_date: String? = "",
    val dob: String? = "",
    val first_name: String? = "",
    val gender_uuid: Int? = 0,
    val is_active: Boolean? = false,
    val is_adult: Boolean? = false,
    val is_dob_auto_calculate: Boolean? = false,
    val last_name: Any? = Any(),
    val middle_name: Any? = Any(),
    val modified_by: Int? = 0,
    val modified_date: String? = "",
    val old_pin: Any? = Any(),
    val package_uuid: Any? = Any(),
    val para_1: Any? = Any(),
    val patient_detail: PatientDetail? = PatientDetail(),
    val patient_type_uuid: Int? = 0,
    val patient_visits: List<PatientVisit?>? = listOf(),
    val period_uuid: Int? = 0,
    val professional_title_uuid: Any? = Any(),
    val registered_date: String? = "",
    val registred_facility_uuid: Int? = 0,
    val revision: Any? = Any(),
    val suffix_uuid: Any? = Any(),
    val tat_end_time: Any? = Any(),
    val tat_start_time: Any? = Any(),
    val title_uuid: Int? = 0,
    val uhid: String? = "",
    val uuid: Int? = 0
)