package com.hmis_tn.doctor.ui.out_patient.model.responseaddpatient

data class ResponseContentaddPatient(
    var age: Int? = 0,
    var application_type_uuid: Int? = 0,
    var blood_group_uuid: Int? = 0,
    var created_by: String? = "",
    var created_date: String? = "",
    var dob: String? = "",
    var fingerPrintData: FingerPrintData? = FingerPrintData(),
    var first_name: String? = "",
    var gender_uuid: Int? = 0,
    var is_active: Boolean? = false,
    var is_adult: Boolean? = false,
    var is_dob_auto_calculate: Boolean? = false,
    var last_name: String? = "",
    var middle_name: String? = "",
    var modified_by: String? = "",
    var modified_date: String? = "",
    var old_pin: Long? = 0,
    var package_uuid: Int? = 0,
    var para_1: Any? = Any(),
    var patient_details: PatientDetails? = PatientDetails(),
    var patient_type_uuid: Int? = 0,
    var patient_visits: PatientVisits? = PatientVisits(),
    var patients: Patients? = Patients(),
    var period_uuid: Int? = 0,
    var professional_title_uuid: Int? = 0,
    var registered_date: String? = "",
    var registred_facility_uuid: String? = "",
    var revision: Boolean? = false,
    var suffix_uuid: Int? = 0,
    var tat_end_time: String? = "",
    var tat_start_time: String? = "",
    var title_uuid: Int? = 0,
    var uhid: String? = "",
    var uuid: Int? = 0,
    var validatedData: ValidatedData? = ValidatedData()
)