package com.hmis_tn.doctor.ui.emr_workflow.radiology.model

data class CreateDetail(
    val created_by: String = "",
    val created_date: String = "",
    val details_comments: String = "",
    val doctor_uuid: String = "",
    val encounter_uuid: String = "",
    val from_department_uuid: String = "",
    val group_uuid: Int = 0,
    val is_active: Boolean = false,
    val is_confidential: Boolean = false,
    val is_ordered: Boolean = false,
    val is_profile: Boolean = false,
    val is_visible_from_facility: Boolean = false,
    val is_visible_to_facility: Boolean = false,
    val lab_master_type_uuid: Int = 0,
    val modified_by: String = "",
    val modified_date: String = "",
    val order_priority_uuid: Int = 0,
    val order_request_date: String = "",
    val order_status_uuid: Int = 0,
    val patient_order_test_details_uuid: Int = 0,
    val patient_order_uuid: Int = 0,
    val patient_uuid: String = "",
    val profile_uuid: Any = Any(),
    val revision: Boolean = false,
    val status: Boolean = false,
    val test_master_uuid: Int = 0,
    val to_department_uuid: Int = 0,
    val to_location_uuid: String = "",
    val to_sub_department_uuid: Int = 0,
    val uuid: Int = 0,
    val vendor_test_uuid: Int = 0
)