package com.hmis_tn.doctor.ui.emr_workflow.radiology.model

class RadiologyListData(

    var favourite_details_id: Int? = null,
    var favourite_display_order: Int? = null,
    var favourite_id: Int? = null,
    var favourite_name: String? = null,
    var test_master_code: String? = null,
    var test_master_description: String? = null,
    var test_master_id: Int? = 0,
    var test_master_name: String? = "",
    var TestMethodId: Int = 0,
    var vital_master_name: Any? = null,
    var vital_master_uom: Any? = null,
    var isSelected: Boolean? = false,
    var itemAppendString: String? = "",
    var position: Int? = 0,
    var duration: String? = "",
    var selectTypeUUID: Int = 0,
    var selectTypeName: String? = null,
    var selectRouteID: Int = 0,
    var selectInvestID: Int = 0,
    var selectToLocationUUID: Int = 0,
    var selectedLocationName: String = "",
    var selectToTestMethodUUID: Int = 0,
    var selectToTestMethodName: String? = null,
    var profile_master_uuid: Int = 0,

    var perdayquantityPrescription: String = "",
    var isFavposition: Int = 0,
    var viewLabstatus: Int = 0,
    var isTemposition: Int = 0,
    var code: String = "",
    var template_id: Int = 1,
    var is_snomed: Int = 0,
    var commands: String = "",
    var diagnosisUUiD: Int = 0,
    var favourite_active: Boolean? = false,
    val favourite_code: String? = "",
    val favourite_type_id: Int? = 0,
    val treatment_kit_id: Int? = 0,

    var lab_id: Int? = 0,
    var lab_name: String? = "",
    var lab_code: String? = "",
    var department_id: Int = 0,
    var template_details_uuid: Int = 0,
    var template_details_displayorder: Int = 0,
    var patient_order_uuid: Int = 0,
    var patient_order_details_uuid: Int = 0,
    var collapse: Boolean = true,
    var Update: Boolean = false,
    var drug_is_emar: Boolean? = false,
    var labDataSelected: Boolean? = false,
    var radiologyDataSelected: Boolean? = false,
    var investigationDataSelected: Boolean? = false,
    var isEditableMode: Boolean? = false,
    var isModifiy: Boolean? = false,
    var isReadyForSave: Boolean? = true
)